### ISSUE TITLE
Vérifications post-programmation

### ISSUE THREAD

**Issue by filorin** [filorin/debgozup#21]
#### Fonctionnalités déjà présentes dans 1.0 
- [x] vérification de la bonne execution du programme
 - [x] installation des logiciels 
 - [x] installation des logiciels non free
   - [x] Flash Player
    - [x] DVD Codec
 - [x] installation de pack d'icones
 - [x] installation & activation d'extensions
 - [x] application des thèmes 

#### Développement spécifiques à 2.0
- [x] vérification de l'intégration de icone de fenetre #14 #8 
- [x] vérification des barres de progression #8 
- [x] vérification des tailles des interfaces #8 
- [x] mise à jour fichier autogen.sh pour dernière version 2.0 #20 
- [x] mise à jour du wiki #19 
- [x] mise à jour des dates et entetes des fichiers
- [x] commentaires dans le code
- [x] diminuer code redondant - optimiser code
- [x] mise à jour de la version dans *install.sh*, *README*, *Wiki* et autres.
- [x] tester fonctionnement *autogen.sh*
